# -*- coding: utf-8 -*-
"""Generate or check the working-context handoff index."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .handoff_databook import Handoff, load_handoffs, sort_handoffs


def render_index(handoffs: list[Handoff]) -> str:
    lines = [
        "# Handoff Index",
        "",
        "Generated by `python -m consulting.tools.ops.status_board`.",
        "Do not edit this file manually; edit individual handoff files instead.",
        "",
    ]

    if not handoffs:
        lines.append("No handoff files found.")
        return "\n".join(lines) + "\n"

    lines.extend([
        "| Timestamp | Surface | Status | Next | Task | Files | Decisions | Handoff |",
        "|---|---|---|---|---|---|---|---|",
    ])
    for handoff in sort_handoffs(handoffs):
        files = _list_cell(handoff.frontmatter.get("files"))
        decisions = _list_cell(handoff.frontmatter.get("decision_ids"))
        lines.append(
            "| {timestamp} | {surface} | {status} | {next_surface} | {task} | {files} | {decisions} | [{name}]({name}) |".format(
                timestamp=_escape(handoff.timestamp),
                surface=_escape(handoff.surface),
                status=_escape(handoff.status),
                next_surface=_escape(handoff.next_surface),
                task=_escape(handoff.task),
                files=files,
                decisions=decisions,
                name=_escape(handoff.path.name),
            )
        )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="status_board",
        description="Generate or check _WORKING_CONTEXT/handoffs/INDEX.md.",
    )
    parser.add_argument(
        "ctx_dir",
        nargs="?",
        default=None,
        help="Working context directory. Defaults to consulting/_WORKING_CONTEXT.",
    )
    parser.add_argument("--check", action="store_true", help="Fail if INDEX.md is stale.")
    args = parser.parse_args()

    ctx_dir = Path(args.ctx_dir) if args.ctx_dir else Path(__file__).resolve().parents[2] / "_WORKING_CONTEXT"
    handoffs_dir = ctx_dir / "handoffs"
    handoffs_dir.mkdir(parents=True, exist_ok=True)
    index_path = handoffs_dir / "INDEX.md"
    expected = render_index(load_handoffs(ctx_dir))

    if args.check:
        if not index_path.exists():
            print(f"ERROR {index_path} does not exist")
            return 1
        actual = index_path.read_text(encoding="utf-8")
        if actual != expected:
            print(f"ERROR {index_path} is stale; run python -m consulting.tools.ops.status_board")
            return 1
        print(f"OK {index_path} is up to date")
        return 0

    index_path.write_text(expected, encoding="utf-8")
    print(f"Wrote {index_path}")
    return 0


def _list_cell(value: object) -> str:
    if not isinstance(value, list) or not value:
        return ""
    return "<br>".join(_escape(str(item)) for item in value)


def _escape(value: str) -> str:
    return value.replace("|", "\\|")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    raise SystemExit(main())
